
#ifndef AVFORMAT_VERSION_H
#define AVFORMAT_VERSION_H

#define LIBAVFORMAT_VERSION_MAJOR 55
#define LIBAVFORMAT_VERSION_MINOR 19
#define LIBAVFORMAT_VERSION_MICRO 104

#endif /* AVFORMAT_VERSION_H */
