package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : libavformat/avformat.h:36</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat") 
public class AVFrac extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public long val() {
		return this.io.getLongField(this, 0);
	}
	@Field(0) 
	public AVFrac val(long val) {
		this.io.setLongField(this, 0, val);
		return this;
	}
	@Field(1) 
	public long num() {
		return this.io.getLongField(this, 1);
	}
	@Field(1) 
	public AVFrac num(long num) {
		this.io.setLongField(this, 1, num);
		return this;
	}
	@Field(2) 
	public long den() {
		return this.io.getLongField(this, 2);
	}
	@Field(2) 
	public AVFrac den(long den) {
		this.io.setLongField(this, 2, den);
		return this;
	}
	public AVFrac() {
		super();
	}
	public AVFrac(Pointer pointer) {
		super(pointer);
	}
}
