package org.ffmpeg.avformat;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : libavformat/avformat.h:6</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVFrac extends Structure {
	public long val;
	public long num;
	public long den;
	public AVFrac() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("val", "num", "den");
	}
	public AVFrac(long val, long num, long den) {
		super();
		this.val = val;
		this.num = num;
		this.den = den;
	}
	public AVFrac(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVFrac implements Structure.ByReference {
		
	};
	public static class ByValue extends AVFrac implements Structure.ByValue {
		
	};
}
