package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.ffmpeg.avutil.AVClass;
/**
 * <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:37</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat") 
public class AVIOContext extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : const AVClass* */
	@Field(0) 
	public Pointer<AVClass > av_class() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : const AVClass* */
	@Field(0) 
	public AVIOContext av_class(Pointer<AVClass > av_class) {
		this.io.setPointerField(this, 0, av_class);
		return this;
	}
	/**
	 * < Start of the buffer.<br>
	 * C type : unsigned char*
	 */
	@Field(1) 
	public Pointer<Byte > buffer() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * < Start of the buffer.<br>
	 * C type : unsigned char*
	 */
	@Field(1) 
	public AVIOContext buffer(Pointer<Byte > buffer) {
		this.io.setPointerField(this, 1, buffer);
		return this;
	}
	/** < Maximum buffer size */
	@Field(2) 
	public int buffer_size() {
		return this.io.getIntField(this, 2);
	}
	/** < Maximum buffer size */
	@Field(2) 
	public AVIOContext buffer_size(int buffer_size) {
		this.io.setIntField(this, 2, buffer_size);
		return this;
	}
	/**
	 * < Current position in the buffer<br>
	 * C type : unsigned char*
	 */
	@Field(3) 
	public Pointer<Byte > buf_ptr() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * < Current position in the buffer<br>
	 * C type : unsigned char*
	 */
	@Field(3) 
	public AVIOContext buf_ptr(Pointer<Byte > buf_ptr) {
		this.io.setPointerField(this, 3, buf_ptr);
		return this;
	}
	/**
	 * < End of the data, may be less than<br>
	 * buffer+buffer_size if the read function returned<br>
	 * less data than requested, e.g. for streams where<br>
	 * no more data has been received yet.<br>
	 * C type : unsigned char*
	 */
	@Field(4) 
	public Pointer<Byte > buf_end() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * < End of the data, may be less than<br>
	 * buffer+buffer_size if the read function returned<br>
	 * less data than requested, e.g. for streams where<br>
	 * no more data has been received yet.<br>
	 * C type : unsigned char*
	 */
	@Field(4) 
	public AVIOContext buf_end(Pointer<Byte > buf_end) {
		this.io.setPointerField(this, 4, buf_end);
		return this;
	}
	/**
	 * < A private pointer, passed to the read/write/seek/...<br>
	 * functions.<br>
	 * C type : void*
	 */
	@Field(5) 
	public Pointer<? > opaque() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * < A private pointer, passed to the read/write/seek/...<br>
	 * functions.<br>
	 * C type : void*
	 */
	@Field(5) 
	public AVIOContext opaque(Pointer<? > opaque) {
		this.io.setPointerField(this, 5, opaque);
		return this;
	}
	/** C type : read_packet_callback* */
	@Field(6) 
	public Pointer<org.ffmpeg.avformat.AVInputFormat.read_packet_callback > read_packet() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : read_packet_callback* */
	@Field(6) 
	public AVIOContext read_packet(Pointer<org.ffmpeg.avformat.AVInputFormat.read_packet_callback > read_packet) {
		this.io.setPointerField(this, 6, read_packet);
		return this;
	}
	/** C type : write_packet_callback* */
	@Field(7) 
	public Pointer<org.ffmpeg.avformat.AVOutputFormat.write_packet_callback > write_packet() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : write_packet_callback* */
	@Field(7) 
	public AVIOContext write_packet(Pointer<org.ffmpeg.avformat.AVOutputFormat.write_packet_callback > write_packet) {
		this.io.setPointerField(this, 7, write_packet);
		return this;
	}
	/** C type : seek_callback* */
	@Field(8) 
	public Pointer<AVIOContext.seek_callback > seek() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : seek_callback* */
	@Field(8) 
	public AVIOContext seek(Pointer<AVIOContext.seek_callback > seek) {
		this.io.setPointerField(this, 8, seek);
		return this;
	}
	/** < position in the file of the current buffer */
	@Field(9) 
	public long pos() {
		return this.io.getLongField(this, 9);
	}
	/** < position in the file of the current buffer */
	@Field(9) 
	public AVIOContext pos(long pos) {
		this.io.setLongField(this, 9, pos);
		return this;
	}
	/** < true if the next seek should flush */
	@Field(10) 
	public int must_flush() {
		return this.io.getIntField(this, 10);
	}
	/** < true if the next seek should flush */
	@Field(10) 
	public AVIOContext must_flush(int must_flush) {
		this.io.setIntField(this, 10, must_flush);
		return this;
	}
	/** < true if eof reached */
	@Field(11) 
	public int eof_reached() {
		return this.io.getIntField(this, 11);
	}
	/** < true if eof reached */
	@Field(11) 
	public AVIOContext eof_reached(int eof_reached) {
		this.io.setIntField(this, 11, eof_reached);
		return this;
	}
	/** < true if open for writing */
	@Field(12) 
	public int write_flag() {
		return this.io.getIntField(this, 12);
	}
	/** < true if open for writing */
	@Field(12) 
	public AVIOContext write_flag(int write_flag) {
		this.io.setIntField(this, 12, write_flag);
		return this;
	}
	@Field(13) 
	public int max_packet_size() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public AVIOContext max_packet_size(int max_packet_size) {
		this.io.setIntField(this, 13, max_packet_size);
		return this;
	}
	@CLong 
	@Field(14) 
	public long checksum() {
		return this.io.getCLongField(this, 14);
	}
	@CLong 
	@Field(14) 
	public AVIOContext checksum(long checksum) {
		this.io.setCLongField(this, 14, checksum);
		return this;
	}
	/** C type : unsigned char* */
	@Field(15) 
	public Pointer<Byte > checksum_ptr() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : unsigned char* */
	@Field(15) 
	public AVIOContext checksum_ptr(Pointer<Byte > checksum_ptr) {
		this.io.setPointerField(this, 15, checksum_ptr);
		return this;
	}
	/** C type : update_checksum_callback* */
	@Field(16) 
	public Pointer<AVIOContext.update_checksum_callback > update_checksum() {
		return this.io.getPointerField(this, 16);
	}
	/** C type : update_checksum_callback* */
	@Field(16) 
	public AVIOContext update_checksum(Pointer<AVIOContext.update_checksum_callback > update_checksum) {
		this.io.setPointerField(this, 16, update_checksum);
		return this;
	}
	/** < contains the error code or 0 if no error happened */
	@Field(17) 
	public int error() {
		return this.io.getIntField(this, 17);
	}
	/** < contains the error code or 0 if no error happened */
	@Field(17) 
	public AVIOContext error(int error) {
		this.io.setIntField(this, 17, error);
		return this;
	}
	/** C type : read_pause_callback* */
	@Field(18) 
	public Pointer<org.ffmpeg.avformat.AVInputFormat.read_pause_callback > read_pause() {
		return this.io.getPointerField(this, 18);
	}
	/** C type : read_pause_callback* */
	@Field(18) 
	public AVIOContext read_pause(Pointer<org.ffmpeg.avformat.AVInputFormat.read_pause_callback > read_pause) {
		this.io.setPointerField(this, 18, read_pause);
		return this;
	}
	/** C type : read_seek_callback* */
	@Field(19) 
	public Pointer<org.ffmpeg.avformat.AVInputFormat.read_seek_callback > read_seek() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : read_seek_callback* */
	@Field(19) 
	public AVIOContext read_seek(Pointer<org.ffmpeg.avformat.AVInputFormat.read_seek_callback > read_seek) {
		this.io.setPointerField(this, 19, read_seek);
		return this;
	}
	@Field(20) 
	public int seekable() {
		return this.io.getIntField(this, 20);
	}
	@Field(20) 
	public AVIOContext seekable(int seekable) {
		this.io.setIntField(this, 20, seekable);
		return this;
	}
	@Field(21) 
	public long maxsize() {
		return this.io.getLongField(this, 21);
	}
	@Field(21) 
	public AVIOContext maxsize(long maxsize) {
		this.io.setLongField(this, 21, maxsize);
		return this;
	}
	@Field(22) 
	public int direct() {
		return this.io.getIntField(this, 22);
	}
	@Field(22) 
	public AVIOContext direct(int direct) {
		this.io.setIntField(this, 22, direct);
		return this;
	}
	@Field(23) 
	public long bytes_read() {
		return this.io.getLongField(this, 23);
	}
	@Field(23) 
	public AVIOContext bytes_read(long bytes_read) {
		this.io.setLongField(this, 23, bytes_read);
		return this;
	}
	@Field(24) 
	public int seek_count() {
		return this.io.getIntField(this, 24);
	}
	@Field(24) 
	public AVIOContext seek_count(int seek_count) {
		this.io.setIntField(this, 24, seek_count);
		return this;
	}
	@Field(25) 
	public int writeout_count() {
		return this.io.getIntField(this, 25);
	}
	@Field(25) 
	public AVIOContext writeout_count(int writeout_count) {
		this.io.setIntField(this, 25, writeout_count);
		return this;
	}
	/** <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:31</i> */
	public static abstract class read_packet_callback extends Callback<read_packet_callback > {
		public int apply(Pointer<? > opaque, Pointer<Byte > buf, int buf_size) {
			return apply(Pointer.getPeer(opaque), Pointer.getPeer(buf), buf_size);
		}
		public int apply(@Ptr long opaque, @Ptr long buf, int buf_size) {
			return apply(Pointer.pointerToAddress(opaque), Pointer.pointerToAddress(buf, Byte.class), buf_size);
		}
	};
	/** <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:32</i> */
	public static abstract class write_packet_callback extends Callback<write_packet_callback > {
		public int apply(Pointer<? > opaque, Pointer<Byte > buf, int buf_size) {
			return apply(Pointer.getPeer(opaque), Pointer.getPeer(buf), buf_size);
		}
		public int apply(@Ptr long opaque, @Ptr long buf, int buf_size) {
			return apply(Pointer.pointerToAddress(opaque), Pointer.pointerToAddress(buf, Byte.class), buf_size);
		}
	};
	/** <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:33</i> */
	public static abstract class seek_callback extends Callback<seek_callback > {
		public long apply(Pointer<? > opaque, long offset, int whence) {
			return apply(Pointer.getPeer(opaque), offset, whence);
		}
		public long apply(@Ptr long opaque, long offset, int whence) {
			return apply(Pointer.pointerToAddress(opaque), offset, whence);
		}
	};
	/** <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:34</i> */
	public static abstract class update_checksum_callback extends Callback<update_checksum_callback > {
		@CLong 
		public long apply(@CLong long checksum, Pointer<Byte > buf, int size) {
			return apply(checksum, Pointer.getPeer(buf), size);
		}
		@CLong 
		public long apply(@CLong long checksum, @Ptr long buf, int size) {
			return apply(checksum, Pointer.pointerToAddress(buf, Byte.class), size);
		}
	};
	/** <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:35</i> */
	public static abstract class read_pause_callback extends Callback<read_pause_callback > {
		public int apply(Pointer<? > opaque, int pause) {
			return apply(Pointer.getPeer(opaque), pause);
		}
		public int apply(@Ptr long opaque, int pause) {
			return apply(Pointer.pointerToAddress(opaque), pause);
		}
	};
	/** <i>native declaration : /home/fschuett/prog/java/eclipse/ffmpeg/csrc/libavformat/avio.h:36</i> */
	public static abstract class read_seek_callback extends Callback<read_seek_callback > {
		public long apply(Pointer<? > opaque, int stream_index, long timestamp, int flags) {
			return apply(Pointer.getPeer(opaque), stream_index, timestamp, flags);
		}
		public long apply(@Ptr long opaque, int stream_index, long timestamp, int flags) {
			return apply(Pointer.pointerToAddress(opaque), stream_index, timestamp, flags);
		}
	};
	public AVIOContext() {
		super();
	}
	public AVIOContext(Pointer pointer) {
		super(pointer);
	}
}
