package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : libavformat/avformat.h:46</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat") 
public class AVProbeData extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : const char* */
	@Field(0) 
	public Pointer<Byte > filename() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : const char* */
	@Field(0) 
	public AVProbeData filename(Pointer<Byte > filename) {
		this.io.setPointerField(this, 0, filename);
		return this;
	}
	/**
	 * < Buffer must have AVPROBE_PADDING_SIZE of extra allocated bytes filled with zero.<br>
	 * C type : unsigned char*
	 */
	@Field(1) 
	public Pointer<Byte > buf() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * < Buffer must have AVPROBE_PADDING_SIZE of extra allocated bytes filled with zero.<br>
	 * C type : unsigned char*
	 */
	@Field(1) 
	public AVProbeData buf(Pointer<Byte > buf) {
		this.io.setPointerField(this, 1, buf);
		return this;
	}
	/** < Size of buf except extra allocated bytes */
	@Field(2) 
	public int buf_size() {
		return this.io.getIntField(this, 2);
	}
	/** < Size of buf except extra allocated bytes */
	@Field(2) 
	public AVProbeData buf_size(int buf_size) {
		this.io.setIntField(this, 2, buf_size);
		return this;
	}
	/**
	 * < mime_type, when known.<br>
	 * C type : const char*
	 */
	@Field(3) 
	public Pointer<Byte > mime_type() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * < mime_type, when known.<br>
	 * C type : const char*
	 */
	@Field(3) 
	public AVProbeData mime_type(Pointer<Byte > mime_type) {
		this.io.setPointerField(this, 3, mime_type);
		return this;
	}
	public AVProbeData() {
		super();
	}
	public AVProbeData(Pointer pointer) {
		super(pointer);
	}
}
