package org.ffmpeg.avformat;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.ffmpeg.avcodec.AvcodecLibrary.AVCodecID;
/**
 * <i>native declaration : libavformat/internal.h:11</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avformat") 
public class CodecMime extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : char[32] */
	@Array({32}) 
	@Field(0) 
	public Pointer<Byte > str() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : AVCodecID */
	@Field(1) 
	public IntValuedEnum<AVCodecID > id() {
		return this.io.getEnumField(this, 1);
	}
	/** C type : AVCodecID */
	@Field(1) 
	public CodecMime id(IntValuedEnum<AVCodecID > id) {
		this.io.setEnumField(this, 1, id);
		return this;
	}
	public CodecMime() {
		super();
	}
	public CodecMime(Pointer pointer) {
		super(pointer);
	}
}
