package org.ffmpeg.avcodec;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Struct;
import org.ffmpeg.avcodec.AvcodecLibrary.AVPacketSideDataType;
import org.ffmpeg.util.AlignmentCustomizer;
/**
 * <i>native declaration : ./libavcodec/avcodec.h:247</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avcodec") 
public class AVPacketSideData extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uint8_t* */
	@Field(0) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : uint8_t* */
	@Field(0) 
	public AVPacketSideData data(Pointer<Byte > data) {
		this.io.setPointerField(this, 0, data);
		return this;
	}
	@Field(1) 
	public int size() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public AVPacketSideData size(int size) {
		this.io.setIntField(this, 1, size);
		return this;
	}
	/** C type : AVPacketSideDataType */
	@Field(2) 
	public IntValuedEnum<AVPacketSideDataType > type() {
		return this.io.getEnumField(this, 2);
	}
	/** C type : AVPacketSideDataType */
	@Field(2) 
	public AVPacketSideData type(IntValuedEnum<AVPacketSideDataType > type) {
		this.io.setEnumField(this, 2, type);
		return this;
	}
	@Struct(customizer=AlignmentCustomizer.class)
	public AVPacketSideData() {
		super();
	}
	@Struct(customizer=AlignmentCustomizer.class)
	public AVPacketSideData(Pointer pointer) {
		super(pointer);
	}
}
