package org.ffmpeg.avcodec;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import org.ffmpeg.avutil.AvutilLibrary.AVBufferRef;
/**
 * <i>native declaration : ./libavcodec/avcodec.h:123</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AVPacket extends Structure {
	/** C type : AVBufferRef* */
	public AVBufferRef buf;
	public long pts;
	public long dts;
	/** C type : uint8_t* */
	public Pointer data;
	public int size;
	public int stream_index;
	public int flags;
	/** C type : void* */
	public Pointer side_data;
	public int side_data_elems;
	public int duration;
	/** C type : destruct_callback* */
	public AVPacket.destruct_callback destruct;
	/** C type : void* */
	public Pointer priv;
	/** < byte position in stream, -1 if unknown */
	public long pos;
	public long convergence_duration;
	/** <i>native declaration : ./libavcodec/avcodec.h:122</i> */
	public interface destruct_callback extends Callback {
		void apply(AVPacket AVPacketPtr1);
	};
	public AVPacket() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("buf", "pts", "dts", "data", "size", "stream_index", "flags", "side_data", "side_data_elems", "duration", "destruct", "priv", "pos", "convergence_duration");
	}
	public AVPacket(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AVPacket implements Structure.ByReference {
		
	};
	public static class ByValue extends AVPacket implements Structure.ByValue {
		
	};
}
